services:
  web:
    build:
      context: .
      dockerfile: cliente.Dockerfile
    ports:
      - "8000:8000"
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8001:8000"
